classDiagram

class Activity {
    +UID
    +Name
    +ExpectedTime
}

class Workshop {
    +Name
    +ExpectedTime
}

class Box {
    +UID
    +Name
}

class Material {
    +UID
    +Name
    +Discription
    +Number
}


class MaterialType {
    +Name
    +ValidateName():void
}

class MaterialTypeRepository {
    -List<MaterialType> MaterialTypes
    Add(MaterialType):void
    Remove(MaterialType):void
    GetByName(string):MaterialType
    GetByUid(string):MaterialType
    ValidateNameDoNotExist(string):bool
}


class MaterialRepository {
    -List<Material> Materials
    +Add(Material):void
    +Remove(Material):void
    +GetByName(string):Material
    +GetByUid(string):Material
    +Get():List<Material>
}

class BoxRepository {
    -List<Box> Boxes
    +Add(Box):void
    +Remove(Box):void
    +GetByName(string):Box
    +GetByUid(string):Box
    +Get():List<Box>
}

class WorkshopRepository {
    -List<Workshop> Workshops
    +Add(Workshop):void
    +Remove(Workshop):void
    +GetByName(string):Workshop
    +GetByUid(string):Workshop
    +Get():List<Workshop>
}


class ActivityRepository {
    -List<Activity> Activities
    +Add(Activity):void
    +Remove(Activity):void
    +GetByName(string):Activity
    +GetByUid(string):Activity
    +Get():List<Activity>
}

class IUidGenerateAble {
    <<interface>>
    +GenerateUid():string
    -ValidateUidIsUniq():bool
}

class UidGenerate {
    +GenerateUid():string
    -ValidateUidIsUniq():bool
}

class Repository {
    <<abstract>>
    +-List<object> Items
    +Add():void
    +Remove():void
    +GetByName(string):object
    +GetByUid(string):object
    +Get():List<object>
}

MaterialType "1..*" --* "1" MaterialTypeRepository
MaterialTypeRepository <|-- Repository : "is"
Material "1" --* "0..*" MaterialRepository : "have"
MaterialRepository <|-- Repository : "is"
Box "0..*" --*  "1" BoxRepository : "have"
BoxRepository <|-- Repository : "is"
Workshop "1..*" --* "1" WorkshopRepository : "have"
WorkshopRepository <|-- Repository : "is"
ActivityRepository <|-- Repository : "is"
Repository --|> IUidGenerateAble : "is"
Activity --* ActivityRepository : "have"

IUidGenerateAble --|> UidGenerate : "is"
