---
config:
  theme: dark
  look: classic
  layout: dagre
title: Domain Model
---
classDiagram
direction LR

class Kasse {
    Navn
    Beskrivelse
}

class Materiale {
    Navn
    Antal
    Beskrivelse
}

class Aktivitet {
    Navn
    Forventet tid
}

class Workshop {
    Navn
}

Kasse "0..1" -- "0..*" Materiale
Materiale "0..*" -- "0..*" Aktivitet
Aktivitet "0..*" -- "0..*" Workshop