---
config:
  theme: dark
  look: classic
title: SD-UC12
---
sequenceDiagram
    Frederik->>+system: 
    system-->>Frederik: 
    Frederik->>system: 
    system-->>Frederik: 
    Frederik->>system: 
    system-->>-Frederik: 
