---
config:
  theme: dark
  look: classic
  layout: dagre
title: SD-UC10
description: |

---
sequenceDiagram
    participant User as Actor
    participant System
    User->>+System: 
    System-->>User: 
    User->>System: 
    System-->>User: 
    User->>System: 
    System-->>-User: 
