---
config:
  theme: dark
  look: classic
  layout: dagre
title: SD-UC2
description: |
    Brugeren opretter et materiale med navn og antal komponenter/dele
    som gemmes i systemet. 
---
sequenceDiagram
    participant User as Actor
    participant System
    User->>+System: Vælger Matrealer
    System-->>User: Matreale-menu
    User->>System: Vælger "Opret materiale"
    System-->>User: Prompter "matreale navn og antal dele"
    User->>System: Indtaster navn og antal dele
    System-->>-User: Returner til matriale-menu
